extend class WT_MainHandler
{
	private transient CVar ForceCustomTags;

	// [Ace] Works for both weapons and monsters.
	static const string TagDefs[] =
	{
		// Mod					// Class			// Custom tag
		"",	"",			""
	};

	private ui string GetCustomTag(class<Actor> cls)
	{
		string CustomTag = "";
		for (int i = 0; i < TagDefs.Size(); i += 3)
		{
			class<Actor> a = TagDefs[i + 1];
			if (cls == a)
			{
				CustomTag = TagDefs[i + 2];
			}
		}
		return CustomTag;
	}
}